//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdeneme2.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    using System.Linq;

    public partial class OgrenciDers
    {
        public int OgrenciId { get; set; }
        public int DersId { get; set; }
        [Display(Name = "Vize")]
        [Required(ErrorMessage = "Bu alan zorunludur")]
        [Range(-1,100,ErrorMessage ="Vize 0 ile 100 arasýnda olmalýdýr")]
        public Nullable<int> Vize { get; set; }
        [Required(ErrorMessage ="Bu alan zorunludur")]
        [Range(-1, 100, ErrorMessage = "Final 0 ile 100 arasýnda olmalýdýr")]
        [Display(Name = "Final")]
        public Nullable<int> Final { get; set; }
        [Display(Name = "Son Not")]
        public Nullable<int> SonNot { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
        
        public void FindSonNot()
        {
            OkulDbEntities db = new OkulDbEntities();
            SonNot = (Vize * 4 + Final * 6) / 10;
            db.OgrenciDers.Add(this);
            db.SaveChanges();
            Ogrenci ogrenci = db.Ogrenci.Find(this.OgrenciId);
            List<OgrenciDers> ogrenciDersler = db.OgrenciDers.Where(x => x.OgrenciId == this.OgrenciId).ToList();
            int ort = 0;
            foreach (var item in ogrenciDersler)
            {
                ort += item.SonNot.Value / ogrenciDersler.Count;
            }
            ogrenci.GenelOrt = ort;
            db.Entry(ogrenci).State = EntityState.Modified;
            db.SaveChanges();
        }
    }
}
