//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdeneme2.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur")]
        [Display(Name = "Ad")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur")]
        [Display(Name = "Soyad")]
        public string Soyad { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur")]
        [Display(Name = "Doğum Tarihi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        [Display(Name = "Cinsiyet")]
        [Required(ErrorMessage = "Bu alan zorunludur")]
        public Nullable<bool> Cinsiyet { get; set; }
        [Display(Name = "Genel Ortalama")]
        public Nullable<int> GenelOrt { get; set; }

        public Nullable<int> SınıfId { get; set; }
    
        public virtual Sinif Sinif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
}
